name: svgo
description: A Dart library for optimizing SVG files. Port of SVGO (Node.js SVG Optimizer).
version: 1.1.0
repository: https://github.com/fluttercandies/svgo
issue_tracker: https://github.com/fluttercandies/svgo/issues
homepage: https://github.com/fluttercandies/svgo

environment:
  sdk: ^3.0.0

dependencies:
  xml: ^6.6.1
  csslib: ^1.0.2
  path: ^1.9.1
  collection: ^1.19.1

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0

topics:
  - svg
  - optimization
  - parser
  - xml
  - graphics
